export const COMPETITION_FIELDS = [
  { name: 'firstName', type: 'text', label: 'First Name', required: false },
  { name: 'lastName', type: 'text', label: 'Last Name', required: false },
  { name: 'email', type: 'email', label: 'Email Address', required: false },
  { name: 'city', type: 'text', label: 'Town/City', required: false },
  { name: 'gender',
    type: 'select',
    label: 'Gender',
    required: false,
    selectOptions: [
      'Male',
      'Female',
    ],
  },
  { name: 'profession',
    type: 'select',
    label: 'Profession',
    required: false,
    selectOptions: [
      'Accountancy, banking and finance',
      'Business, consulting and management',
      'Charity and voluntary work',
      'Creative arts and design',
      'Energy and utilities',
      'Engineering and manufacturing',
      'Healthcare',
      'Hospitality and events management',
      'Information technology',
      'Law',
      'Public services',
      'Leasure, sport and tourism',
      'Marketing, advertising and PR',
      'Media and internet',
      'Propery and construction',
      'Recruitment and HR',
      'Retail',
      'Sales',
      'Science and pharmeceuticals',
      'Social care',
      'Teacher training and education',
      'Transport and logisitcs',
      'Other',
    ],
  },
  {
    name: 'age',
    type: 'select',
    label: 'Age',
    required: false,
    selectOptions: [
      '10-20 years',
      '20-30 years',
      '30-40 years',
      '40-50 years',
      '50-60 years',
      '60-70 years',
      '70+ years',
    ],
  },
  { name: 'previous',
    type: 'checkbox',
    label: 'Have you previously purchased mid-century, antique or upcycled furniture online?',
    required: false,
  },
  {
    name: 'prize',
    type: 'select',
    label: 'Which prize would you like to enter to win?',
    selectOptions: [
      '1', '2', '3',
    ],
  },
  { name: 'antiSpam', type: 'hidden', label: 'antiSpam', required: false },
];

export const DEALER_SIGNUP_FIELDS = [
  { name: 'listingValue',
  type: 'select', label: 'How much would you like to list?', required: true,
  selectOptions: [
    'Up to £2,000 - FREE',
    'Up to £8,000 - £50 per month',
    'Up to £10,000 - £100 per month',
    'Up to £20,000 - £150 per month',
    ' Up to £30,000 - £200 per month',
  ],
},
  { name: 'name', type: 'text', label: 'Your Name', required: true },
  { name: 'businessName', type: 'text', label: 'Business Name', required: false },
  { name: 'website', type: 'text', label: 'Website (if applicable)', required: false },
  { name: 'email', type: 'email', label: 'Email Address', required: true },
  { name: 'city', type: 'text', label: 'Town/City', required: true },
  { name: 'favePlatform',
    type: 'select', label: 'What\'s your preferred platform to sell on?', required: true,
    selectOptions: [
      'eBay',
      'Etsy',
      'Vinterior',
      'Others?',
    ],
  },
  { name: 'reason', type: 'select', label: 'What do you like about it?', required: true,
    selectOptions: [
      'Low effort to maintain',
      'Low costs',
      'Lots of sales',
    ],
  },
  { name: 'averagePrice',
    type: 'select', label: 'What\'s the average price of your items?', required: true,
    selectOptions: [
      '<£50',
      '£50 - £100',
      '£100 - £300',
      '£300 - £800',
      '£800 - £1500',
      '£1500+',
    ],
  },
  { name: 'shopfront',
    type: 'select', label: 'Would you like a personalised shopfront?', required: true,
    selectOptions: [
      'Yes',
      'No',
    ],
  },
  { name: 'fees',
    type: 'select',
    label: 'Roughly how much do you pay in fees to all of the platforms that you sell on?',
    required: false,
    selectOptions: [
      '<£100 per month',
      '£100 - £250 per month',
      '£250 - £500 per month',
      '£500 - £1000 per month',
      '£1000 - £2000 per month',
      '£2000+ per month',
    ],
  },
];
