export const COMPETITION_FIELDS = [
  { name: 'firstName', type: 'text', label: 'First Name', required: false },
  { name: 'lastName', type: 'text', label: 'Last Name', required: false },
  { name: 'email', type: 'email', label: 'Email Address', required: false },
  { name: 'city', type: 'text', label: 'Town/City', required: false },
  { name: 'profession',
    type: 'select',
    label: 'Profession',
    required: false,
    selectOptions: [
      'Accountancy, banking and finance',
      'Business, consulting and management',
      'Charity and voluntary work',
      'Creative arts and design',
      'Energy and utilities',
      'Engineering and manufacturing',
      'Healthcare',
      'Hospitality and events management',
      'Information technology',
      'Law',
      'Public services',
      'Leasure, sport and tourism',
      'Marketing, advertising and PR',
      'Media and internet',
      'Propery and construction',
      'Recruitment and HR',
      'Retail',
      'Sales',
      'Science and pharmeceuticals',
      'Social care',
      'Teacher training and education',
      'Transport and logisitcs',
      'Other',
    ],
  },
  {
    name: 'age',
    type: 'select',
    label: 'Age',
    required: false,
    selectOptions: ['10-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80'],
  },
  { name: 'antiSpam', type: 'hidden', label: 'antiSpam', required: false },
];

export const DEALER_SIGNUP_FIELDS = [
  { name: 'name', type: 'text', label: 'Your Name', required: true },
  { name: 'businessName', type: 'text', label: 'Business Name', required: false },
  { name: 'website', type: 'text', label: 'Website (if applicable)', required: false },
  { name: 'email', type: 'email', label: 'Email Address', required: true },
  { name: 'city', type: 'text', label: 'Town/City', required: true },
  { name: 'favePlatform',
    type: 'select', label: 'What\'s your favourite platform to sell on?', required: true,
    selectOptions: [
      'eBay',
      'Etsy',
      'Vinterior',
      'Others?',
    ],
  },
  { name: 'reason', type: 'select', label: 'Why? change to checkboxes?', required: true,
    selectOptions: [
      'Good user interface',
      'Low effort to maintain',
      'Low costs',
      'Lots of sales',
    ],
  },
  { name: 'listingValue',
    type: 'select', label: 'How much would you like to list?', required: true,
    selectOptions: [
      '<5k',
      '5k - 10k',
      '10k - 20k',
      '20k - 30k',
      '30k+',
    ],
  },
  { name: 'averagePrice',
    type: 'select', label: 'What\'s the average price of your items?', required: true,
    selectOptions: [
      '<£50',
      '£50 - £100',
      '£100 - £300',
      '£300 - £800',
      '£800 - £1500',
      '£1500+',
    ],
  },
  { name: 'shopfront',
    type: 'select', label: 'Would you like a personalised shopfront?', required: true,
    selectOptions: [
      'Yes',
      'No',
    ],
  },
  { name: 'fees',
    type: 'select',
    label: 'Roughly how much do you pay in fees to all of the platforms that you sell on?',
    required: false,
    selectOptions: [
      '<£100 per month',
      '£100 - £250 per month',
      '£250 - £500 per month',
      '£500 - £1000 per month',
      '£1000 - £2000 per month',
      '£2000+ per month',
    ],
  },
];
